// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CookiesController from "./cookies_controller"
application.register("cookies", CookiesController)

import Landing__GalleryController from "./landing/gallery_controller"
application.register("landing--gallery", Landing__GalleryController)

import Landing__IndexController from "./landing/index_controller"
application.register("landing--index", Landing__IndexController)

import TurboFrameHistoryController from "./turbo_frame_history_controller"
application.register("turbo-frame-history", TurboFrameHistoryController)
