model:
  validate:
    email: presence
    name: presence
    password: presence
  decorator:
  association:
  active_storage:
  enum:
    role:
      admin:
        value: 0
      manager:
        value: 1

app:
  title: Користувач системи
  index:
    conditions:
      - email:
          sign: eq
    list:
      fields:
        - email
        - name
        - role
      default_order:
    csv:
      fields:
  show:
    fields:
      - email
      - name
      - role
      - created_at
      - updated_at
  form:
    fields:
      - email:
          kind: email
      - name
      - role:
          kind: select
      - password:
          kind: password

  association_search:
    conditions:
      - name:
          sign: full_like
    list:
        fields:
          - id
          - name
