model:
  validate:
    title:
      - presence
    order_id:
      - numericality:
          allow_nil: true
  association:
    admin_user:
      kind: belongs_to
      name_field: name
    expense_category:
      kind: belongs_to
      name_field: title

app:
  title: Надходження (витрати)
  index:
    conditions:
      - admin_user_id:
          sign: eq
          form_kind: association_search
      - expense_category:
          sign: eq
          form_kind: association_search
    list:
      fields:
        - id
        - admin_user_id
        - description
        - amount
      default_order:
        field: id
        kind: desc
  show:
    fields:
      - id
      - admin_user
      - description
      - amount
      - order_id

  form:
    fields:
      - admin_user:
          kind: association_search
      - expense_category:
          kind: association_search
      - amount
      - title
      - description:
          kind: text_area
