model:
  validate:
    title:
      - presence
    description:
      - presence
    flow:
      - presence
  association:
    expense:
      kind: has_many
      dependent: destroy
#######
app:
  title: Категорія доходів (витрат)
  index:
    conditions:
      - title:
          sign: full_like
          form_kind: text
    list:
      fields:
        - id
        - title
        - description
      default_order:
        field: id
        kind: asc
  show:
    fields:
      - title
      - description
  form:
    fields:
      - title
      - description
