model:
  validate:
    title:
      - presence
    description:
      - presence
    flow:
      - presence
  association:
    expense:
      kind: has_many
      dependent: destroy
  enum:
    flow:
      income:
        value: 0
        color: lime
      outcome:
        value: 1
        color: red
#######
app:
  title: Категорія доходів (витрат)
  index:
    conditions:
      - title:
          sign: full_like
          form_kind: text
      - flow:
          sign: any
          form_kind: checkbox
    list:
      fields:
        - id
        - title
        - description
        - flow
      default_order:
        field: id
        kind: asc
  show:
    fields:
      - title
      - description
      - flow
  form:
    fields:
      - title
      - description
      - flow:
          kind: radio
