model:
  validate:
    title:
      - presence
  association:
    admin_user:
      kind: belongs_to
      name_field: name
    money_flow_category:
      kind: belongs_to
      name_field: title
    money_flow_details:
      kind: has_many
      dependent: destroy
      model: # Associated models (order_details) can also be set
        validate:
          money_flow_category: presence
        association: # Further associations to order_details (product)
          money_flow_category:
            kind: belongs_to
            name_field: title

app:
  title: Надходження (витрати)
  index:
    conditions:
      - admin_user_id:
          sign: eq
          form_kind: association_search
      - money_flow_category:
          sign: eq
          form_kind: association_search
    list:
      fields:
        - id
        - admin_user_id
        - description
        - total_amount
      default_order:
        field: id
        kind: desc
  show:
    fields:
      - id
      - admin_user
      - description
      - total_amount
      - money_flow_details:
          kind: association
          fields:
            - money_flow_category_id
            - amount
            - order_id
  form:
    fields:
      - admin_user:
          kind: association_search
      - money_flow_details:
          kind: association
          fields:
            - money_flow_category:
                kind: association_search
            - amount
      - title
      - description:
            kind: text_area

#model:
#  # Define validation here
#  validate:
#    amount: presence
#    price:
#      - presence
#      - numericality:
#          greater_than_or_equal_to: 0
#  # Define Enum here
#  enum:
#    status:
#      ordered:
#        value: 1
#        color: blue
#      charged:
#        value: 2
#        color: pink
#  # Define decorator here
#  decorator:
#    price:
#      prepend: $
#      digit: true
#  # Define association here
#  association:
#    customer:
#      kind: belongs_to
#      name_field: name
#    order_details:
#      kind: has_many
#      dependent: destroy
#      # If the child model on the has_many side also needs to be configured, define it here.
#      model:
#        validate:
#        enum:
#        decorator:
#        association:
#  # Define active_storage here
#  active_storage:
#    photo:
#      kind: image
#app:
#  title: MONEY FLOWS
#  # index view settings (search condition, list and csv)
#  index:
#    conditions:
#      - id:
#          sign: eq
#      - status:
#          sign: any
#          form_kind: checkbox
#    list:
#      fields:
#        - id
#        - customer
#        - status
#      default_order:
#        field: id
#        kind: desc
#    csv:
#      # If fields is empty, all fields are covered. (The show view is the same)
#      fields:
#  # show view settings
#  show:
#    fields:
#      - id
#      - customer
#      - order_details:
#          fields:
#            - product
#            - amount
#  # form view settings
#  form:
#    fields:
#      - status:
#          kind: radio
#      - customer:
#          kind: association_search
#      #Bulk registration of has_many
#      - order_details:
#          kind: association
#          fields:
#            - product
#                kind: association_search
#            - amount
#  # Child screen search for related models
#  association_search:
#    conditions:
#      - id:
#          sign: eq
#    list:
#      fields:
#        - id
#        - title
