model:
  validate:
    price:
      - presence
    status:
      - presence
    paid:
      - presence
    dead_date:
      - presence
    dead_time:
      - presence

  association:
    customer:
      kind: belongs_to
      name_field: name
    admin_user:
      kind: belongs_to
      name_field: name
    order_details:
      kind: has_many
      dependent: destroy
      model: # Associated models (order_details) can also be set
        validate:
          service: presence
        association: # Further associations to order_details (product)
          service:
            kind: belongs_to
            name_field: title
  enum:
    status:
      new:
        value: 0
        color: lime
      in_work:
        value: 1
        color: pink
      done:
        value: 2
        color: green
      rejected:
        value: 3
        color: blue
    paid:
      unpaid:
        value: 0
        color: red
      inpaid:
        value: 1
        color: lime

app:
  title: Замовлення
  index:
    conditions:
      - customer_id:
          sign: eq
          form_kind: association_search
      - admin_user_id:
            sign: eq
            form_kind: association_search
      - status:
          sign: any
          form_kind: checkbox
      - paid:
          sign: any
          form_kind: checkbox
    
    list:
      fields:
        - id
        - customer_id
        - admin_user_id
        - status
        - paid
        - price
        - dead_date
        - dead_time
      default_order:
        field: id
        kind: desc

  show:
    fields:
      - id
      - customer
      - admin_user
      - status
      - paid
      - price
      - dead_date
      - dead_time
      - description
      - order_details:
          kind: association
          fields:
            - service

  form:
    fields:
      - customer_id:
          kind: association_search
      - admin_user_id:
          kind: association_search
      - order_details:
          kind: association
          fields:
            - service_id:
                kind: association_search
      - price:
          kind: number
      - description
      - dead_date:
          kind: date
      - dead_time:
          kind: time
      - status:
          kind: radio
      - paid:
          kind: radio
